services:

  nodejs:
    container_name: nodejs
    restart: always
    build:
      context: ./backend-express
      args:
        NODE_PORT: 3000
    ports:
      - 3000:3000
    volumes:
      - ./app:/var/
      - /var/node_modules

  mongo:
    container_name: mongo
    build:
      context: ./backend-mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./backend-mongo/data/db:/data/db

  nginx:
    container_name: nginx
    build:
      context: ./server-nginx
    ports:
      - "80:80"
    depends_on:
      - nodejs
      - mongo