services:

  nodejs:
    container_name: nodejs
    restart: always
    build:
      context: .
      args:
        NODE_PORT: 3000
    ports:
      - 3000:3000
    volumes:
      - .:/var/
      - /var/node_modules