FROM nginx:latest
COPY ./index.html /usr/share/nginx/html/index.html
COPY ./filters.html /usr/share/nginx/html/filters.html
COPY ./frontend.js /usr/share/nginx/html/frontend.js
COPY ./default.conf /etc/nginx/conf.d/default.conf